In [2]:
import math

In [8]:
print(math.sin(90))
print(math.cos(90))
print(math.factorial(3))

0.8939966636005579
-0.4480736161291701
6


In [9]:
math.pi

3.141592653589793

In [10]:
math.degrees(math.pi)

180.0

In [11]:
help(math.degrees)

Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



In [12]:
import numpy as np

In [13]:
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
lst = np.array(lst)

In [17]:
print(np.max(lst))

8150


In [20]:
filtro = lst > 4999
vendite_maggiori_4999 = lst[filtro]
print(vendite_maggiori_4999)
print(vendite_maggiori_4999.size)

[5500 7200 6410 8150 7100 5350]
6


In [21]:
filtro_2 = lst < 3000
vendite_minori_3000 = lst[filtro_2]
print(vendite_minori_3000)

[2000 1280 1900 2500]


In [22]:
print(np.mean(lst))

4634.166666666667


In [23]:
stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] )

In [26]:
for i in range(len(stipendi)):
    stipendi[i] *= 2
print(stipendi)

[ 200  400  600  800 1000 1200 1400 1600 1800 2000]


In [27]:
stipendi * 2

array([ 400,  800, 1200, 1600, 2000, 2400, 2800, 3200, 3600, 4000])